name: Release

on:
  # release daily at 8am UTC (midnight or 1am pacific)
  # https://crontab-generator.org/
  schedule:
    - cron: '0 8 * * *'
  # or manual trigger
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.repo_pat }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn
      - run: yarn build
      - run: yarn test
      - run: |
          git config user.email "kchau@microsoft.com"
          git config user.name "Ken Chau"
      - run: yarn release -y -n $NPM_AUTHTOKEN
        env:
          NPM_AUTHTOKEN: ${{ secrets.npm_authtoken }}
